name: Blox Fruits Stock

on:
  schedule:
    # ทุก 2 ชั่วโมง
    - cron: "5 */2 * * *"

  workflow_dispatch:

jobs:

  stock-check:

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # Checkout
      # ------------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # Python
      # ------------------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ------------------------------------------------------
      # Install dependencies
      # ------------------------------------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------------------------------------------------
      # Run bot
      # ------------------------------------------------------

      - name: Run Blox Fruits Stock Bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

        run: |
          python main.py
